---
default_config:

frontend:
  themes: !include_dir_merge_named themes

logger:
  logs:
    custom_components.gbb: debug

# gbb_health
sensor:
  - platform: gbb
    id: 020166bc-5eb3-4a30-9f5a-356d15a3ee09
    name: Healthcheck
    interval: 00:00:10
    grace_period: 00:00:30
    # required:
    #   - gummi
    ignore:
      - person.admin
      - conversation.home_assistant
      - tts.*

# gbb_thermostat
input_number:
  temperature:
    name: Temperature
    initial: 20
    min: 0
    max: 40
    step: 1

input_boolean:
  radiator:
    name: Radiator
  force_fallback_mode:
    name: Force fallback
  simulate_unavailable:
    name: Simulate Unavailable

template:
  - sensor:
      - name: Temperature
        state: >
          {% if is_state('input_boolean.simulate_unavailable', 'on') %}
            unavailable
          {% else %}
            {{ states('input_number.temperature') }}
          {% endif %}

climate:
  - platform: gbb
    name: Thermostat
    target_sensor: sensor.temperature
    heater: input_boolean.radiator
    min_temp: 16
    max_temp: 24
    ac_mode: false
    target_temp: 20
    hot_tolerance: 0.3  # How much it over shoots
    min_cycle_duration:
      seconds: 1
    initial_hvac_mode: "heat"
    precision: 1
    fallback_on_ratio: 0.2
    fallback_interval: 00:00:30
    fallback_force_switch: input_boolean.force_fallback_mode
