---
name: CI

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - lint-mypy
          - lint-ruff
          - lint-imports
          - test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Run ${{ matrix.target }}
        run: make ${{ matrix.target }}

      - name: Upload test coverage
        uses: codecov/codecov-action@v5
        if: matrix.target == 'test'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
