---
name: TOX

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    name: Run HA ${{ matrix.target }} tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - 2024.8.0
          - 2024.8.1
          - 2024.8.2
          - 2024.8.3
          - 2024.9.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        uses: jdx/mise-action@v2

      - name: Run ${{ matrix.target }}
        run: HA_VERSION=${{ matrix.target }} make tox-env
