---
name: TOX

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    name: Run HA ${{ matrix.target }} tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - 2025.8.0

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Run ${{ matrix.target }}
        run: HA_VERSION=${{ matrix.target }} make tox-env
